PAYMENT_DATA_KEY = "payments"

PAYMENT_ADDRESS = 0
PAYMENT_AMOUNT = 1
PAYMENT_DATELASTPAID = 2
PAYMENT_WHEN = 3
PAYMENT_COUNT0 = 4
PAYMENT_COUNTn = 5
PAYMENT_DATECREATED = 6
PAYMENT_DESCRIPTION = 7
PAYMENT_ID = 8
PAYMENT_DATEUPDATED = 9
PAYMENT_DATENEXTPAID = 10
PAYMENT_DATESOVERDUE = 11
PAYMENT_ENTRY_LENGTH = 12

ACTION_PAY = 1
ACTION_FORGET = 2

